### ISSUE TITLE
More flexibility for specifying the openAPI config file

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/openapi#1]
Since `openapi_server/2` must be used as a directive, I don't know how to supply the configuration `File` argument.  Is it possible to first determine the file location, e.g., by using `absolute_file_name/[2,3]`, prior to performing the term expansion?

I've hacked around this a bit by introducing one line to `openapi.pl`, but this may be not be the best way to handle this:
```prolog
expand_openapi_server(File0, Options,
                      [ (:- discontiguous((openapi_handler/9,
                                           openapi_doc/2,
                                           openapi_error_hook/3)))
                      | Clauses
                      ]) :-
    absolute_file_name(File0, File, [access(read)]), % Line added.
    read_openapi_spec(File, Spec, Options, Options1),
    phrase(server_clauses(Spec, Options1), Clauses).
```

**Comment by JanWielemaker** [comment]
?  The absolute_file_name/3 is already in `read_openapi_spec/4`, including an option 
`relative_to(Dir)`, so the first place it looks is in the same dir as the Prolog file that loads
it.

**Comment by wouterbeek** [comment]
oops, this indeed works just fine...
