### ISSUE TITLE
Generate servern with swi-openapi

### ISSUE THREAD

**Issue by kassepro1** [JanWielemaker/openapi#3]
When i run the command to generate server a have this error attached 

./swi-openapi --server=server.pl spec.yaml
![erroswiopenapi](https://user-images.githubusercontent.com/32929345/89742141-93a1e900-da97-11ea-9a0a-9c5ed229e6c5.png)

**Comment by JanWielemaker** [comment]
You didn't install this as a pack (see pack_install/1)?   You can also achieve that by creating a symlink from the `~/.local/share/swi-prolog/pack` directory.

**Comment by kassepro1** [comment]
Thanks you
