### ISSUE TITLE
I'm trying to make a server from a test case, I get such an error, I can't generate the server either.

### ISSUE THREAD

**Issue by heiheshang** [JanWielemaker/openapi#6]
I'm trying to make a server from a test case, I get such an error, I can't generate the server either.
`?- openapi_doc('/home/oper/Programs/openapi/examples/petstore/petstore.yaml', server, [httpd(true),ui(true),server('/home/oper/Programs/tracker_server/server_rpc.pl'),file('/home/oper/Programs/tracker_server/server_rpc.pl')]).
ERROR: source_sink `''' does not exist (Ð ÑÐ°ÐºÐ¾Ð³Ð¾ Ñ
                                                       Ð°Ð¹Ð»Ð° Ð¸Ð»Ð¸ ÐºÐ°ÑÐ°Ð»Ð¾Ð³Ð°)
ERROR: In:
ERROR:   [27] open('',read,_1712,[encoding(utf8)])
ERROR:   [26] <meta call>
ERROR:   [25] sig_atomic(openapi:open('',read,_1786,...)) <foreign>
ERROR:   [24] setup_call_cleanup(openapi:open('',read,_1830,...),openapi:json_read_dict(_1842,_1844),openapi:close(_1854)) at /usr/local/lib/swipl/boot/init.pl:679
ERROR:   [22] openapi:url_type('#/components/schemas/Pet',_1886) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:1657
ERROR:   [21] openapi:json_type(yaml{'$ref':"#/components/schemas/Pet"},_1918,[base_uri('#/components/schemas/Pets'),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:1613
ERROR:   [16] openapi:'__aux_maplist/3_response+2'([200- ...,...],[response(200,data,...,...,_2016,"An paged array of pets")|_2004],_1978,[yaml(...),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:206
ERROR:   [15] openapi:path_handler('/pets',get,yaml{operationId:"listPets",parameters:[...],responses:yaml{200: ...,default: ...},summary:"List all pets",tags:["pets"]},openapi_handler(get,['/pets'],[],[],[...],_2134,-,[...|_2160],_2140,_2142),[yaml(...),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:236
ERROR:   [14] openapi:path_handlers([get- ...,...],'/pets',[yaml(...),...|...],_2212,_2214) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:195
ERROR:   [12] openapi:server_path_clauses(['/pets'- ...,...],[yaml(...),...|...],_2282,_2284) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:175
ERROR:   [11] openapi:server_clauses(yaml{components:yaml{schemas: ...},info:yaml{license: ...,title:"Swagger Petstore",version:"1.0.0"},openapi:"3.0.0",paths:yaml{'/pets': ...,'/pets/{petId}': ...},servers:[...]},[yaml(...),...|...],[openapi_root('/v1')|_2442],[]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:164
ERROR:   [10] openapi:openapi_doc('/home/oper/Programs/openapi/examples/petstore/petstore.yaml',server,[httpd(true),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:1682
ERROR:    [9] toplevel_call(user:user: ...) at /usr/local/lib/swipl/boot/toplevel.pl:1173
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
`

**Comment by JanWielemaker** [comment]
Looks like some kind of encoding issue.    Without all info to replicate the case it is hard to say anything sensible.

**Comment by heiheshang** [comment]
What can I do ?
` >locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
`

**Comment by heiheshang** [comment]
`?- current_prolog_flag(encoding,X).
X = utf8.
`

**Comment by JanWielemaker** [comment]
The error suggest an encoding issue.  Looks like UTF-8 printed as ASCII.   Anyway, it looks like it tries to find something in a file with a zero-length ('') name.    That is wrong.    Possibly your OpenAPI spec is wrong, possibly there is a bug in dereferencing a type.     I don't know, but without something to reproduce it is hard to make any sense of this.    I'd first try the spec with another openapi tool to make sure the spec is correct.

**Comment by heiheshang** [comment]
hmm, but I took the example from the example folder

**Comment by JanWielemaker** [comment]
As long as you don't explain exactly what you did such that it can be reproduced, this is not going to work.  Sorry.

**Comment by heiheshang** [comment]
I tried to follow what is written in the readme
`swi-openapi --ui --httpd --server=server.pl petstore.yaml`

**Comment by heiheshang** [comment]
`?- openapi_doc('/home/oper/Programs/openapi/examples/petstore/petstore.yaml', server, [httpd(true),ui(true),server('/home/oper/Programs/tracker_server/server_rpc.pl'),file('/home/oper/Programs/tracker_server/server_rpc.pl')]).
ERROR: source_sink `''' does not exist (No such file or directory)
ERROR: In:
ERROR:   [27] open('',read,_1712,[encoding(utf8)])
ERROR:   [26] <meta call>
ERROR:   [25] sig_atomic(openapi:open('',read,_1786,...)) <foreign>
ERROR:   [24] setup_call_cleanup(openapi:open('',read,_1830,...),openapi:json_read_dict(_1842,_1844),openapi:close(_1854)) at /usr/local/lib/swipl/boot/init.pl:679
ERROR:   [22] openapi:url_type('#/components/schemas/Pet',_1886) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:1657
ERROR:   [21] openapi:json_type(yaml{'$ref':"#/components/schemas/Pet"},_1918,[base_uri('#/components/schemas/Pets'),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:1613
ERROR:   [16] openapi:'__aux_maplist/3_response+2'([200- ...,...],[response(200,data,...,...,_2016,"An paged array of pets")|_2004],_1978,[yaml(...),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:206
ERROR:   [15] openapi:path_handler('/pets',get,yaml{operationId:"listPets",parameters:[...],responses:yaml{200: ...,default: ...},summary:"List all pets",tags:["pets"]},openapi_handler(get,['/pets'],[],[],[...],_2134,-,[...|_2160],_2140,_2142),[yaml(...),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:236
ERROR:   [14] openapi:path_handlers([get- ...,...],'/pets',[yaml(...),...|...],_2212,_2214) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:195
ERROR:   [12] openapi:server_path_clauses(['/pets'- ...,...],[yaml(...),...|...],_2282,_2284) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:175
ERROR:   [11] openapi:server_clauses(yaml{components:yaml{schemas: ...},info:yaml{license: ...,title:"Swagger Petstore",version:"1.0.0"},openapi:"3.0.0",paths:yaml{'/pets': ...,'/pets/{petId}': ...},servers:[...]},[yaml(...),...|...],[openapi_root('/v1')|_2442],[]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:164
ERROR:   [10] openapi:openapi_doc('/home/oper/Programs/openapi/examples/petstore/petstore.yaml',server,[httpd(true),...|...]) at /home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:1682
ERROR:    [9] toplevel_call(user:user: ...) at /usr/local/lib/swipl/boot/toplevel.pl:1173
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
`

**Comment by JanWielemaker** [comment]
Turns out the pack was not updated after this was fixed long ago in the git version.   Just updated the pack to version 0.2.1.   Please upgrade to that or install from the git version.
