### ISSUE TITLE
unable to build executable

### ISSUE THREAD

**Issue by heiheshang** [JanWielemaker/openapi#7]
unable to build executable due to --no-pce option, is it fundamentally using a graphical debugger ?
`LANG=C.UTF-8 swipl \
	--stand_alone=true	\
	--no-pce	\
	--undefined=error	\
	--verbose=false	\
	--on_error=status	\
	--on_warning=status	\
	--foreign=save	\
	-o server_rpc.qlf	\
	-c server_rpc.pl
% Disabled autoloading (loaded 160 files)
% Disabled autoloading (loaded 8 files)
% Disabled autoloading (loaded 0 files)
ERROR: The predicates below are not defined. If these are defined
ERROR: at runtime using assert/1, use :- dynamic Name/Arity.
ERROR: 
ERROR: openapi:gtrace/0, which is referenced by
ERROR: 	/home/oper/.local/share/swi-prolog/pack/openapi/prolog/openapi.pl:2178:4: 1-st clause of openapi:start_debugger/0`

**Comment by JanWielemaker** [comment]
Made the use optional.   Means you need to install from the git version.
